# Generated by Django 3.1.7 on 2021-03-18 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fragrances_api', '0002_auto_20210318_1651'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Upload',
        ),
        migrations.RenameField(
            model_name='book',
            old_name='cover',
            new_name='product_img',
        ),
        migrations.AddField(
            model_name='book',
            name='product_category',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='book',
            name='product_price',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='book',
            name='product_size',
            field=models.TextField(blank=True),
        ),
    ]
