# Generated by Django 3.1.7 on 2021-03-22 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fragrances_api', '0003_auto_20210318_1709'),
    ]

    operations = [
        migrations.CreateModel(
            name='Addproduct',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.TextField(blank=True)),
                ('product_price', models.TextField(blank=True)),
                ('product_category', models.TextField(blank=True)),
                ('product_size', models.TextField(blank=True)),
                ('product_img', models.ImageField(blank=True, null=True, upload_to='./addproduct/')),
            ],
        ),
        migrations.DeleteModel(
            name='Book',
        ),
    ]
